### PR TITLE
feat: add helm section

### PR DESCRIPTION
**Pull request by lplit**

### CODE REVIEW

**Comment by rubenfiszel** [comment]
Infra AWS is private to us and contains our own deployment code. For anything public, we might as well include it in the main repo

**Comment by lplit** [comment]
WDYT about publishing the chart and referencing that in the doc instead? 

https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by rubenfiszel** [comment]
@lplit I see now that it is to setup an helm repositories. If we were to go this route, then i'd much rather have it be it's own dedicated public repository. I will create one.

**Comment by lplit** [comment]
Marty is setting up the gh-pages distribution, I updated the links. 

@rubenfiszel

**Pull request merged**
